# Generated by Django 4.0.1 on 2022-02-22 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_order_order_time_order_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
