# Generated by Django 4.0.1 on 2022-02-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.CharField(choices=[('Japanese_Food', 'Japanese_Food'), ('Beverage', 'Beverage'), ('Western_food', 'Western_food')], default='Japanese_Food', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash')], default='credit card', max_length=50),
        ),
    ]
