# Generated by Django 4.0.1 on 2022-02-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_order_order_item_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
