# Generated by Django 4.0.1 on 2022-02-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_order_order_item_order_order_type1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
