# Generated by Django 4.0.1 on 2022-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_order_order_date_alter_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
