# Generated by Django 4.0.1 on 2022-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_type2',
            new_name='Beverage',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type1',
            new_name='Japanese_food',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type3',
            new_name='Rice_Dishes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type4',
            new_name='Vegetarian',
        ),
        migrations.AddField(
            model_name='order',
            name='Beverage_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Contact_number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='Japanese_food_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Rice_Dishes_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Vegetarian_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
