# Generated by Django 4.0.1 on 2022-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_order_type2_order_beverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Taking_method',
            field=models.CharField(choices=[('Dine in', 'Dine in'), ('Take away', 'Take away')], default='None', max_length=50),
        ),
    ]
