# Generated by Django 4.0.1 on 2022-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_order_taking_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(default='None', max_length=50)),
                ('Comment', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
