# Generated by Django 4.0.1 on 2022-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Nickname',
            field=models.CharField(max_length=50),
        ),
    ]
